Crud_Livros/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mainLivros/', include("mainLivros.urls", namespace="mainLivros")),
]

mainLivros/urls.py
from django.urls import path
from . import views

app_name = "mainLivros"

urlpatterns = [
    path("", views.LivroList.as_view(), name="list"),
    path("create/", views.LivroCreate.as_view(), name="create"),
    path("update/<int:pk>/", views.LivroUpdate.as_view(), name="update"),
    path("detail/<int:pk>/", views.LivroDetail.as_view(), name="detail"),
    path("delete/<int:pk>/", views.LivroDelete.as_view(), name="delete"),
]

mainLivros/models.py
from enum import auto
from django.db import models


class Livro(models.Model):
    titulo = models.CharField(max_length=255, unique=True)
    qtdPaginas = models.IntegerField()
    isbn = models.CharField(max_length=40)
    autores = models.TextField()
    editora = models.CharField(max_length=150)

    def __str__(self) -> str:
        return self.titulo

mainLivros/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from .models import Livro


class LivroList(ListView):
    model = Livro


class LivroDetail(DetailView):
    model = Livro


class LivroCreate(CreateView):
    model = Livro
    fields = '__all__'
    success_url = reverse_lazy('mainLivros:list')


class LivroUpdate(UpdateView):
    model = Livro
    fields = '__all__'
    success_url = reverse_lazy('mainLivros:list')


class LivroDelete(DeleteView):
    model = Livro
    fields = '__all__'
    success_url = reverse_lazy('mainLivros:list')

mainLivros/templates/mainLivros/base.html
<!DOCTYPE html>

<html>

<head>
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <header>
    <header>
</body>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</html>

mainLivros/templates/mainLivros/livro_confirm_delete.html
{% extends 'mainLivros/base.html' %}

{% block title %} Deletar Livro {% endblock %}

{% block content %}
    <h1> Tem certeza que deseja remover o Livro '{{livro.titulo}}' </h1>
    <form method="post" action".">
        {% csrf_token %}
        <input type="submit" value="Sim, tenho certeza">
        <input type="reset" value="Calcelar" onclick="location.href = '{% url 'mainLivros:list' %}'">
    </form>

{% endblock %}

mainLivros/templates/mainLivros/livro_detail.html
{% extends 'mainLivros/base.html' %}

{% block title %}  {% endblock %}

{% block content %}
    <input type="submit" value="Voltar" onclick="location.href = '{% url 'mainLivros:list' %}'">
    <article>
        <h2>{{livro.titulo}}</h2>
        <p>Quantidade de paginas: {{livro.qtdPaginas}}</p>
        <p>ISBN: {{livro.isbn}}</p>
        <p>Autores: {{livro.autores}}</p>
        <p>Editora: {{livro.editora}}</p>
    </article>
{% endblock %}

mainLivros/templates/mainLivros/livro_form.html
{% extends 'mainLivros/base.html' %}

{% block title %} Cadastro Livro {% endblock %}

{% block content %}
    <h1> Cadastro de Livro </h1>
    <form method="post" action".">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Salvar">
        <input type="reset" value="Calcelar" onclick="location.href = '{% url 'mainLivros:list' %}'">
    </form>

{% endblock %}

mainLivros/templates/mainLivros/livro_list.html
{% extends 'mainLivros/base.html' %}

{% block title %} Lista de livros {% endblock %}

{% block content %}
    <input type="submit" value="Cadastrar" onclick="location.href = '{% url 'mainLivros:create' %}'">
    <ul>
        {% for livro in livro_list %}
            <li>{{livro.titulo}} 
                - <a href="{% url 'mainLivros:update' pk=livro.id %}">Editar</a> 
                - <a href="{% url 'mainLivros:detail' pk=livro.id %}">Vizualizar</a>
                - <a href="{% url 'mainLivros:delete' pk=livro.id %}">Deletar</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}